export const UserRoles = {
  Manager: { id: 1, name: "Manager" },
  canGetLookups: { id: 2, name: "canGetLookups" },
  canAddLookups: { id: 3, name: "canAddLookups" },
  canUpdateLookups: { id: 4, name: "canUpdateLookups" },
  canDeleteLookups: { id: 5, name: "canDeleteLookups" },
  canGetUserGroups: { id: 6, name: "canGetUserGroups" },
  canAddUserGroup: { id: 7, name: "canAddUserGroup" },
  canUpdateUserGroup: { id: 8, name: "canUpdateUserGroup" },
  canDeleteUserGroup: { id: 9, name: "canDeleteUserGroup" },
  canViewUsers: { id: 10, name: "canViewUsers" },
  canEditUsers: { id: 11, name: "canEditUsers" },
  canAddUsers: { id: 12, name: "canAddUsers" },
  canChangePassword: { name: "canChangePassword", id: 13 },
  canGetCurrentUser: { name: "canGetCurrentUser", id: 14 },
  canUpdateUser: { name: "canUpdateUser", id: 15 },
  canDeleteUser: { name: "canDeleteUser", id: 16 },
  canAddUser: { name: "canAddUser", id: 17 },
  canGetAllUsers: { name: "canGetAllUsers", id: 18 },
  canGetUserById: { name: "canGetUserById", id: 19 },
  Employee: { name: "Employee", id: 20 },
};
